export const actioType = {
    FEATCHING_START: 'FEATCHING_START',
    FEATCHING_SUCCES: 'FEATCHING_SUCCES',
    FEATCHING_ERROR: 'FEATCHING_ERROR',
    ADD_TO_CART: 'ADD_TO_CART',
    ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
    DELETE_TO_CART: 'DELETE_TO_CART'

}